######################
# PseudoMusic Config #
######################

# DO NOT CHANGE THIS LINE! YOUR CONFIG WILL BE RESET UPON LOADING IF THIS LINE IS EDITED!
Version: 6


##########
# Player #
##########

# Global or private player?
PlayerType: private

# Auto-start next song?
Playlist: true

# Playlist delay (in seconds)
PlaylistDelay: 5


#########
# Music #
#########

# Song Folder Path (From PseudoMusic Plugin Folder)
SongPath: songs

# Last Page Button
LastPageMaterial: Paper
# Number between 0-8
LastPageLocation: 0

# Next Page Button
NextPageMaterial: Paper
# Number between 0-8
NextPageLocation: 8

# Last Song Button
LastSongMaterial: Feather
# Number between 0-8
LastSongLocation: 2

# Next Song Button
NextSongMaterial: Feather
# Number between 0-8
NextSongLocation: 6

# Stop Button
StopMaterial: Barrier
# Number between 0-8
StopLocation: 4

# Play Button
# Replaces stop button when no music is playing
PlayMaterial: Jukebox

# Repeat Button
RepeatMaterial: Arrow
# Number between 0-8
RepeatLocation: 1

# Stop Repeat Button
# Replaces repeat button when music is repeating
StopRepeatMaterial: Structure_Void

# Shuffle Button
ShuffleMaterial: Magenta_Glazed_Terracotta
# Number between 0-8
ShuffleLocation: 7

# Disable Shuffle Button
# Replaces shuffle button when music is shuffling
StopShuffleMaterial: Structure_Void

# Restart song to beginning if offline for specified amount of time (in seconds)
# Set to -1 to always restart the song at last position
RestartSongIfOfflineFor: 60


###########
# BossBar #
###########

# Use BossBar to show current song?
BossBar: true

# How long should the BossBar be visible? (in seconds) (0 stays on while song is playing)
BarVisibility: 0

# How frequenty should the bar be updated (in ticks)
# Increase this number if your server is lagging!
BarUpdate: 10


#########
# Title #
#########

# Use Title to show current song?
Title: true

# How long should the title be visible? (in seconds)
TitleVisibility: 5

# Title fade in/out time (in ticks)
TitleFade: 10