name: ${project.artifactId}
author: PseudoResonance
main: io.github.pseudoresonance.pseudomusic.PseudoMusic
version: ${revision}
description: Adds the ability to play music to players
api-version: 1.13
depend: [PseudoAPI,NoteBlockAPI]
commands:
  pseudomusic:
    description: PseudoMusic Menu
    aliases: [music]
permissions:
  pseudomusic.reload:
    description: Allows the player to reload the plugin
    default: op
  pseudomusic.reset:
    description: Allows the player to reset the config
    default: op
    children:
      pseudomusic.reload: true
  pseudomusic.reloadlocalization:
    description: Allows the player to reload the localization
    default: op
  pseudomusic.resetlocalization:
    description: Allows the player to reset the localization
    default: op
    children:
      pseudomusic.reloadlocalization: true
  pseudomusic.browse:
    description: Allows the player to browse music
    default: true
  pseudomusic.play:
    description: Allows the player to start music
    default: true
  pseudomusic.stop:
    description: Allows the player to stop music
    default: true
  pseudomusic.repeat:
    description: Allows the player to repeat music
    default: true
  pseudomusic.shuffle:
    description: Allows the player to shuffle music
    default: true
  pseudomusic.*:
    description: Gives the user all PseudoMusic permissions
    default: op
    children:
      pseudomusic.reset: true
      pseudomusic.resetlocalization: true
      pseudomusic.reload: true
      pseudomusic.browse: true
      pseudomusic.play: true
      pseudomusic.stop: true
      pseudomusic.repeat: true
      pseudomusic.shuffle: true